CREATE DATABASE QLBANHANG
GO

CREATE TABLE LOAISP
(
	MALOAI CHAR(5) PRIMARY KEY,
	TENLOAI NVARCHAR(50)
)

CREATE TABLE SANPHAM
(
	MASP CHAR(5) PRIMARY KEY,
	TENSP NVARCHAR(50),
	MOTA NVARCHAR(50),
	GIA INT,
	MALOAI CHAR(5) FOREIGN KEY REFERENCES LOAISP(MALOAI)
)

CREATE TABLE KHACHHANG
(
	MAKH CHAR(5) PRIMARY KEY,
	TENKH NVARCHAR(50),
	DC NVARCHAR(50),
	DT VARCHAR(11)
)

CREATE TABLE DONDH
(
	SODDH CHAR(5) PRIMARY KEY,
	NGAYDAT DATE,
	MAKH CHAR(5) FOREIGN KEY REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CTDDH
(
	SODDH CHAR(5) FOREIGN KEY REFERENCES DONDH(SODDH),
	MASP CHAR(5)  FOREIGN KEY REFERENCES SANPHAM(MASP),
	PRIMARY KEY(SODDH, MASP),
	SOLUONG INT
)

CREATE TABLE NGUYENLIEU
(
	MANL CHAR(5) PRIMARY KEY,
	TENNL NVARCHAR(50),
	DVT NVARCHAR(50),
	GIA INT
)

CREATE TABLE LAM 
(
	MANL CHAR(5) FOREIGN KEY REFERENCES NGUYENLIEU(MANL),
	MASP CHAR(5) FOREIGN KEY REFERENCES SANPHAM(MASP),
	PRIMARY KEY(MANL, MASP),
	SOLUONG FLOAT
)
--VIEW
--a)	Danh sách các loại sản phẩm có nhiều sản phẩm nhất (Tên loại SP, số sản phẩm)
CREATE VIEW V1
AS
SELECT TOP 1 TENSP, SUM(SOLUONG) AS [SỐ LƯỢNG SẢN PHẨM]
FROM SANPHAM A, CTDDH B
WHERE A.MASP = B.MASP 
GROUP BY TENSP

SELECT* FROM V1

--b)	Danh sách khách hàng không đặt hàng trong tháng 3/2010 (Tên KH, địa chỉ).
CREATE VIEW V2
AS
SELECT MAKH, TENKH
FROM KHACHHANG A
WHERE A.MAKH NOT IN(SELECT B.MAKH 
					FROM DONDH B INNER JOIN CTDDH C
					ON B.SODDH = C.SODDH
					WHERE MONTH(NGAYDAT) = '3' AND YEAR(NGAYDAT) = '2010')

SELECT* FROM V2
--c)	DS khách hàng đặt nhiều đơn đặt hàng nhất trong tháng 3/2010 (Tên KH, địa chỉ).
CREATE VIEW V3
AS
SELECT TOP 1 TENKH, DC, COUNT(B.SODDH) AS [SỐ ĐƠN ĐẶT HÀNG]
FROM KHACHHANG A, DONDH B
WHERE A.MAKH = B.MAKH  AND MONTH(NGAYDAT) = '3' AND YEAR(NGAYDAT) = '2010'
GROUP BY TENKH, DC
ORDER BY COUNT(B.SODDH) DESC

SELECT* FROM V3

--d)	Danh sách các sản phẩm không được đặt trong tháng 3/2010 (Tên SP, mô tả).
CREATE VIEW V4
AS
SELECT TENSP, MOTA
FROM SANPHAM A
WHERE A.MASP NOT IN(SELECT A.MASP 
					FROM CTDDH B INNER JOIN DONDH C
					ON B.SODDH = C.SODDH
					WHERE MONTH(NGAYDAT) = '3' AND YEAR(NGAYDAT) = '2010')

SELECT* FROM V4

--e)	Danh sách khách hàng có đặt trên 10 cái tủ DDA (Tên KH, địa chỉ, tổng số lượng).
CREATE VIEW V5
AS
SELECT TENKH, DC, SUM(SOLUONG) AS [TỔNG SỐ LƯỢNG]
FROM KHACHHANG A, DONDH B, CTDDH C
WHERE A.MAKH = B.MAKH AND B.SODDH = C.SODDH AND MASP = 'SP03'
GROUP BY TENKH, DC
HAVING SUM(SOLUONG) > 10

SELECT* FROM V5

--f)	DS các sản phẩm được làm từ nhiều loại nguyên liệu nhất (Tên SP, Giá, Số loại).
CREATE VIEW V6
AS
SELECT TOP 1 C.TENSP, C.GIA, COUNT(A.MANL) AS [SỐ LOẠI]
FROM NGUYENLIEU A, LAM B, SANPHAM C
WHERE A.MANL = B.MANL AND B.MASP = C.MASP
GROUP BY C.TENSP, C.GIA
ORDER BY COUNT(A.MANL) DESC

SELECT* FROM V6

--g)	Danh sách các sản phẩm có giá thành SX hơn 1 triệu (Tên SP, Giá thành SX).
CREATE VIEW V7
AS
SELECT TENSP, SUM(C.GIA) AS [GIÁ THÀNH SX]
FROM SANPHAM A, LAM B, NGUYENLIEU C
WHERE  A.MASP = B.MASP AND B.MANL = C.MANL
GROUP BY TENSP
HAVING SUM(C.GIA) > 1000000

SELECT* FROM V7

--h)	DS các sản phẩm có lãi trên 20% (Tên SP, Giá thành SX, Giá bán, phần trăm lãi)
CREATE VIEW V8
AS
SELECT TENSP, SUM(C.GIA) AS [GIÁ THÀNH SX], A.GIA AS [GIÁ BÁN], (SUM(A.GIA - C.GIA) * 0.2)   AS [LÃI 20%]
FROM SANPHAM A, LAM B, NGUYENLIEU C, CTDDH D
WHERE A.MASP = B.MASP AND A.MASP = D.MASP AND B.MANL = C.MANL 
GROUP BY TENSP, A.GIA


SELECT* FROM V8

--i)	Danh sách đơn đặt hàng có tổng số tiền lớn hơn 100 triệu (Số DDH, Ngày đặt, Tổng tiền).
CREATE VIEW V9
AS
SELECT C.SODDH, NGAYDAT, SUM(SOLUONG*A.GIA) AS [TỔNG TIỀN]
FROM SANPHAM A, CTDDH B, DONDH C
WHERE A.MASP = B.MASP AND B.SODDH = C.SODDH
GROUP BY C.SODDH, NGAYDAT
HAVING  SUM(SOLUONG*A.GIA) > 100000000

SELECT* FROM V9

--j)	Danh sách các loại nguyên liệu dùng để làm tất cả các sản phẩm (TênNL, Giá).
CREATE VIEW V10
AS
SELECT TENNL, GIA
FROM NGUYENLIEU A
WHERE A.MANL IN (SELECT B.MANL
			     FROM LAM B RIGHT JOIN SANPHAM C
			     ON B.MASP = C.MASP)

SELECT* FROM V10

--k)	Danh sách khách hàng có đặt tất cả các sản phẩm (Tên KH, DC).
CREATE VIEW V11
AS
SELECT TENKH, DC
FROM KHACHHANG A
WHERE A.MAKH IN (SELECT B.MAKH
				 FROM DONDH B, CTDDH C, SANPHAM D
				 WHERE B.SODDH = C.SODDH AND C.MASP = D.MASP)

SELECT* FROM V11

--l)	Danh sách các sản phẩm tất cả các khách hàng đều đặt (Tên SP, Mô tả).
CREATE VIEW V12
AS
SELECT TENSP, MOTA
FROM SANPHAM A
WHERE A.MASP IN (SELECT B.MASP
				 FROM  CTDDH B, DONDH C, KHACHHANG D
				 WHERE B.SODDH = C.SODDH AND C.MAKH = D.MAKH)

SELECT* FROM V12
--m)	Danh sách khách hàng lâu nhất chưa đặt hàng (Tên KH, địa chỉ).
CREATE VIEW V13
AS
SELECT        TOP (1) dbo.KHACHHANG.TENKH, dbo.KHACHHANG.DC
FROM            dbo.KHACHHANG INNER JOIN
                         dbo.DONDH ON dbo.KHACHHANG.MAKH = dbo.DONDH.MAKH INNER JOIN
                         dbo.CTDDH ON dbo.DONDH.SODDH = dbo.CTDDH.SODDH
ORDER BY dbo.DONDH.NGAYDAT
SELECT* FROM V13
----procedure
--a) Liệt kê DS khách hàng (TênKH, DC) có đặt hàng vào Ngày tháng năm X.
create proc P1(@X date)
as
begin
    select TENKH, DC
    from KHACHHANG K, DONDH D
    where K.MAKH = D.MAKH and CAST(NgayDat as date) = CAST(@X as date)
end
--b) Liệt kê DS khách hàng (TênKH, DC) có đặt hàng sản phẩm có mã số X.
create proc P2(@X varchar(10))
as
begin
    select TenKH, DC
    from KHACHHANG K, DONDH D, CTDDH C
    where K.MAKH = D.MAKH and D.SoDDH = C.SoDDH and C.MaSP = @X
end

